  services:
    mosquitto:
      container_name: mosquitto
      image: eclipse-mosquitto 
      ports:
        - "1883:1883"

    consumer:
      container_name: consumer
      build:
        context: .
        dockerfile: dockerfiles/consumer.dockerfile
      env_file:
       -.env
      depends_on:
        timescaledb:
          condition: service_healthy

    timescaledb:
      image: timescaledb/timescaledb:latest-pg18
      container_name: timescaledb
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "5432:5432"
      volumes:
        - timescaledb_data:/var/lib/postgresql
      healthcheck:
        test: ["CMD-SHELL", "pg-isready -U ${POSTGRES_USER} -d {POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 10

             





    
